using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class movetile : MonoBehaviour

{
private float timer=0;
//SerializeField‚ğ‚Â‚¯‚é‚±‚Æ‚ÅUnityã‚Émax time ‚ğ’²®‚Å‚«‚é‚æ‚¤‚É
[SerializeField]private float maxTime=10.0f;
private bool moveFlag=true;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        //1ƒtƒŒ[ƒ€‚²‚Æ‚ÌŠÔ‚ğTIme‚É‰ÁZ
        timer+=Time.deltaTime;
        if(timer>=maxTime)
        {
            timer=0;
            //True‚¾‚Á‚½ê‡‚ÍFalse‚ğ‘ã“ü
            //False‚¾‚Á‚½ê‡‚ÍTrue‚ğ‘ã“ü
            moveFlag=!moveFlag;
        }
        if(moveFlag)
        {
            transform.position+=new Vector3(1*Time.deltaTime,0,0);
        }
        else{
            transform.position-=new Vector3(1*Time.deltaTime,0,0);
        }
    }
}
